### ISSUE TITLE
PLayers are shaky on host screen

### ISSUE THREAD

**Issue by HiiJustin** [WarrenHood/SlidingCompany#1]
When mod is installed along side other mods, it seems to cause the player models of other players to shake drastically on the host screen, but not the other players.

**Comment by ybeauchamph** [comment]
I'm having the same issue, but not totally isolated to the host screen, clients can also see each other shaking especially when entering the building.
Also the shaking players are not showing up at their actual coordinate.

I recorded a video, the host is on the right side:

https://github.com/WarrenHood/SlidingCompany/assets/5566222/a7a8f033-3e96-4cc2-aeef-5bbb92c32009

One interesting thing I have found is if you have PushCompany, the shaking stop when you get pushed.

**Comment by WarrenHood** [comment]
I am aware of this issue, just found it today when trying it in multiplayer for the first time. I'll only be able to try fixing this when I get back after January 3rd.

**Comment by WarrenHood** [comment]
Actually, tried a quick fix, and from a quick test it seems to have fixed the issue, can you guys update to 1.0.6 and confirm this is still an issue?

**Comment by ybeauchamph** [comment]
Seems to be fixed, thank you!

**Comment by WarrenHood** [comment]
Great! Closing this
